# Allow anonymous access for local development
allow_anonymous true

# Standard MQTT port (For ESP)
listener 1883
protocol mqtt

# WebSocket port (Required for Web App)
listener 9001
protocol websockets
